energySoaps = {'activities': ['pedaling a generator',
                           'installing solar panels',
                           'exercising',
                           'sleeping',
                           'installing solar panels on roof',
                           'unplugging appliances when not in use',
                           'Eating Food',
                           'Running',
                           'plug in cord',
                           'run on treadmill'],
            'objects': ['battery',
                        'electric plug',
                        'battey',
                        'solar panel',
                        'solar panels',
                        'power outlet',
                        'Battery',
                        'Solar Cells',
                        'outlet',
                        'calorie'],
            'people': ['dad: pay energy bills',
                       'electrician: set up electricity',
                       'electrical engineer',
                       'secretary of energy',
                       'professional: fixing panels to roof of home',
                       'mom: unplugging microwave',
                       'Electrical Engineer',
                       'Power plant manager',
                       'meter reader',
                       'Benjamin Franklin with kite'],
            'settings': ['garage (where the meter is)',
                         'desert',
                         'power plant',
                         'solar plant',
                         'roof of home',
                         'kitchen in home',
                         'Power Plant',
                         'Grocery store',
                         'gym',
                         'computer lab']}