 fallSoaps = {'activities': ['raking leaves',
                                  'cornfield maze',
                                  'raking leaves',
                                  'baking pies',
                                  'carving pumpkins',
                                  'jumping in leaf piles',
                                  'raking yard',
                                  'buying a backpack',
                                  'Hiking',
                                  'Raking leaves'],
                   'objects': ['colored leaf',
                               'scarecrow',
                               'pumpkin spice drinks',
                               'leaves',
                               'pumpkins',
                               'scarecrow',
                               'leaves',
                               'school supplies',
                               'Pumpkin Pie',
                               'Fall leaves'],
                   'people': ['harvesting farmer',
                              'football player',
                              'family: making Thanksgiving dinner',
                              'gardener: clipping trees',
                              'halloween store owner',
                              'corn husker',
                              'mom: getting kids ready to go to school',
                              'teacher: preparing classroom',
                              'Mother: baking',
                              'Children: playing in leaves'],
                   'settings': ['football game',
                                'homecoming dance',
                                'backyard',
                                'kitchen',
                                'forest',
                                'corn field',
                                'forest (with leaves on ground)',
                                'busy school with children',
                                'Suburban backyard',
                                'Hiking trail']}