fashionSoaps =  {'activities': ['shopping',
                            'designing clothes',
                            'Modeling clothing',
                            'Photo shoot',
                            'shopping, modeling, designing, sewing',
                            '{}',
                            'Shopping for Clothes',
                            'Trying on new clothes',
                            'going shopping for summer attire',
                            'dressing for fashion show'],
             'objects': ['clothes',
                         'accessories (bracelets, necklace, watch)',
                         'Dress',
                         'Shoes',
                         'clothes, purses, jewelry, hats, make up',
                         '{}',
                         'Clothing',
                         'Mannequin',
                         'clothes',
                         'runway'],
             'people': ['designer: sketching ideas',
                        'seamstress: sewing clothes',
                        'Model: Modeling famous clothes lines',
                        'Celebrity: Wearing famous designers clothing',
                        'models, designers, sales associates,seamtress, make up artist',
                        '{}',
                        'Women: shopping',
                        'Fashion models: walking down runway',
                        'parents: shopping for kids',
                        'model: walking down runway'],
             'settings': ['workshop',
                          'office',
                          'Runway Show',
                          'Red Carpet appearances',
                          'shops, model runways, sewing room,',
                          '{}',
                          'Shopping mall',
                          'Fashion show',
                          'city mall',
                          'private hall']}
