halloweenSoaps = {'activities': ['trick-or-treating',
                              'scaring people',
                              'Trick or Treating, parties, carving jack o  lanterns, Fall Festivals, parties',
                              '{}',
                              'going trick or treat',
                              'bobbing for apples',
                              'going trick or treating',
                              'visiting haunted house',
                              'Trick or treating',
                              '{}'],
               'objects': ['pumpkin',
                           'skeleton',
                           'masks, pumpkins, candy, decorations, costumes, fall leaves, paper bags',
                           '{}',
                           'jackolantern',
                           'costume',
                           'candy',
                           'costumes',
                           'Pumpkin',
                           'Jack-o-lantern'],
               'people': ['homeowners: passing out candy',
                          'children: putting on costumes',
                          'parents, children, neighbors, friends,',
                          '{}',
                          'witch (costumed)',
                          'frankenstein',
                          'kids: knocking on doors',
                          'parents: giving candy out to neighbors',
                          'Kids',
                          'Adults'],
               'settings': ['neighborhood',
                            'amusement park',
                            'schools, home, neighborhoods',
                            '{}',
                            'halloween party',
                            'haunted house',
                            'haunted house',
                            'houses in neighborhood',
                            'Suburbs',
                            'Local neighborhood']}