healthySoaps =  {'activities': ['yoga class, jogging cycling, walking, sleeping,',
                            '{}',
                            'going to gym',
                            'cooking healthy foods',
                            'Working out',
                            'Preparing salad',
                            'lifting weights',
                            'running',
                            'Exercising',
                            'Eating well'],
             'objects': ['yoga mat, doctor, medicine, free weights, jogging shoes',
                         '{}',
                         'exercise machine',
                         'vegetables',
                         'Greens and vegetables',
                         'Fitness equipment',
                         'apple',
                         'scale',
                         'Vegetables',
                         'Vitamins'],
             'people': ['doctors, nurses, yoga instructor, DVD fitness instructor',
                        '{}',
                        'trainer: teaching people how to work out',
                        'parent: making healthy snacks for kids',
                        'Fitness trainer: helping train',
                        'Chef preparing healthy foods',
                        'trainer: monitoring exercise',
                        'yoga instructor: teaching class',
                        'Doctor',
                        'Personal Trainer'],
             'settings': ['gym, doctors office, home, YMCA, outdoor track',
                          '{}',
                          'private gym',
                          'at home in the kitchen',
                          "Farmer's market",
                          'Working out outdoors',
                          'gym',
                          'home (in front of tv)',
                          "Doctor's office",
                          'Gym']}