imaginationSoaps = {'activities': ['improv',
                                'drawing',
                                '{}',
                                '{}',
                                'playing with blocks',
                                'writing a book',
                                'Painting',
                                'Brainstorming',
                                'writing story',
                                'painting picture'],
                 'objects': ['rainbow',
                             'unicorn',
                             'Brain',
                             'Light bulb',
                             'book',
                             'toys',
                             'surreal paintings',
                             'Mythical creatures',
                             'diary',
                             'blank paper'],
                 'people': ['artist: sketching',
                            'writer: worldbuilding',
                            '{}',
                            '{}',
                            'actors',
                            'inventor',
                            'Dancers',
                            'Hand Christian Anderson characters',
                            'imaginary friend',
                            'drama instructor'],
                 'settings': ['desk',
                              'classroom',
                              '{}',
                              '{}',
                              'preschool play area',
                              'library book time',
                              'Alice in Wonderland',
                              'Willy Wonka and the Chocolate factory',
                              'art room',
                              'classroom']}