natureSoaps = {'activities': ['hiking',
                           'camping',
                           'Hiking',
                           'Camping',
                           'hiking',
                           'picking up trash',
                           'hiking',
                           'bird watching',
                           'hiking',
                           'camping'],
            'objects': ['pinecones',
                        'trees',
                        'Trees',
                        'Mountains',
                        'trees',
                        'river',
                        'trees',
                        'mountains',
                        'tree',
                        'bird'],
            'people': ['ranger: protecting forest',
                       'gardener: planting flowers',
                       'Native American: Caring for Land',
                       'Hunter: Cleaning Up',
                       'ranger: watching over state park',
                       'volunteer: cleaning up garbage',
                       'park ranger: maintain national parks for people to visit and experience',
                       'biologist: learn more about the natural world in a scientific fashion',
                       'park ranger: patrolling state and national parks',
                       'cub scout leader: teaching children about nature'],
            'settings': ['forest preserve',
                         'campground',
                         'Waterfall',
                         'Mountain Top',
                         'National Park',
                         'forest',
                         'national parks',
                         'Beach',
                         'forests',
                         'lake']}