newYearsSoaps = {'activities': ['counting down',
                                        'eating grapes',
                                        'partying',
                                        'making drinks',
                                        'drinking',
                                        'watching fireworks',
                                        'watching the clock reach midnight',
                                        'eating and drinking',
                                        'People celebrating',
                                        'Holding parties'],
                         'objects': ['Big Apple',
                                     'confetti',
                                     'drinking glasses',
                                     'party hats',
                                     'fireworks',
                                     'champagne bottles',
                                     'funny hats',
                                     'kazoos',
                                     'Champagne glasses',
                                     'Countdown ball'],
                         'people': ['singer: performing concert',
                                    'videographer: videotaping the Apple',
                                    'friends, having fun',
                                    'woman, partying',
                                    'spouse: being available for the midnight kiss',
                                    'friend: hosting the party',
                                    'mom: cooking dinner',
                                    'brother: showing best youtube videos of the year',
                                    'Party host',
                                    'Party attendees'],
                         'settings': ['Times Square',
                                      'a club',
                                      'a bar',
                                      'at a house',
                                      "friend's house",
                                      'city park for fireworks',
                                      'house party',
                                      'time square',
                                      'Times Square',
                                      'New Years Eve Party']}