nightSoaps = {'activities': ['Sleeping',
                          'Watching TV',
                          'Star-gazing',
                          'Sleeping',
                          'using telescope to view the moon and stars',
                          'going to sleep',
                          'sleeping',
                          '{}',
                          'clubbing',
                          'sleeping'],
           'objects': ['Moon',
                       'Stars',
                       'Lamp or flashlight',
                       'Stars',
                       'moon',
                       'bed',
                       'moon',
                       '{}',
                       'moon',
                       'streetlight'],
           'people': ['Couples',
                      'Children: Sleeping',
                      'Mom: making dinner',
                      'Me: reading a book before bed',
                      'student: studying the stars',
                      'parents: putting kids to sleep',
                      'watchmen',
                      '{}',
                      'taxi driver: driving people home',
                      'parents: putting kids to bed'],
           'settings': ['Bedroom in home',
                        'House',
                        'Dreams',
                        'Laying in bed',
                        'outside in the backyard',
                        'inside bedroom',
                        'woods',
                        '{}',
                        'nightclub',
                        'bedroom']}