springSoaps = {'activities': ['playing',
                                    'gardening',
                                    'gardening',
                                    'picnics',
                                    'jumping rope',
                                    'riding a bike',
                                    'Gardening',
                                    'Hunting for Easter Eggs',
                                    'Food planting',
                                    'Easter egg hunt'],
                     'objects': ['flowers',
                                 'baby animals',
                                 'flowers',
                                 'grass',
                                 'flowers',
                                 'birds',
                                 'Flowers',
                                 'Grass',
                                 'Flowers',
                                 'Easter'],
                     'people': ['children :playing',
                                'farmers:tending to fields',
                                'mom: planting flowers',
                                'dad: mowing lawn',
                                'lanscaper',
                                'gardening',
                                'Childern',
                                'Women: Planting flowers',
                                'Easter bunny',
                                'Easter egg making'],
                     'settings': ['grassy fields',
                                  'farms',
                                  'picnic in a park',
                                  'a grassy hill',
                                  'playground',
                                  'park',
                                  'Meadow',
                                  'Garden',
                                  'Easter baskets opening for kids',
                                  'Green meadows']}