summerSoaps = {
    objects: [
        'beach',
        'pool',
        'Beach ball',
        'Sand and piers',
        'watering can',
        'bbq grill',
        'ice cream',
        'sunglasses',
        'Garden hose',
        'Lawnmower',  
    ],
    people: [
        'tanning at the beach',
        'swimming at the pool',
        'Swimming in the ocean',
        'Traveling by car on vacation',
        'swimming',
        'playing tennis',
        'swimming in a pool',
        'going to the beach',
        'Swimming at beach',
        'Celebrating 4th of July',
    ],
    activities: [
        'lifeguard: saving people from drowning',
        'students: taking vacation from school',
        'Family: on vacation together',
        'People in bathing suits',
        'lifeguards: protecting swimmers',
        'baseball manager:  coaching players',
        'lifeguard: watching the pool',
        'swimming instructor: teaching children',
        'Friends playing beach volleyball',
        'Couple: sailing',
    ],
    settings: [
        'laying on the sand (at beach)',
        'public swimming pool in neighborhood',
        'Vacation: sitting on a beach',
        'Hot days, sweating',
        'beach',
        'baseball stadium',
        'pool',
        'beach',
        'Pool',
        'Backyard barbecue'
    ],      
}
