valentinesSoaps = {
    objects: [
        'Flowers',
        'Jewelry',
        'cards',
        'candy',
        'chocolate box',
        'flowers',
        'chocolate',
        'flowers',
        'candy',
        'stuffed animals' ,
    ],
    people: [
        'Romantic dinner date',
        'Engagement',
        'dating',
        'kissing',
        'making romantic dinner',
        'purchasing roses for spouse',
        'having a romantic dinner',
        'movie date',
        'dining at resturants',
        'kissing',
    ],
    activities: [
        'Man: taking woman out on a date',
        'Woman: asking girlfriend to marry her',
        'girlfriend: get stuff',
        'boyfriend: give stuff',
        'wife: making dessert',
        'husband: buying gift',
        'boyfriend: giving gifts',
        'girlfriend: making chocolate',
        'husbands',
        'giving presents',
    ],
    settings: [
        'A moon lit walk on the beach.',
        'A quiet booth for two.',
        'romantic restaurant',
        'bar',
        'at home',
        'at flower shop',
        'restaurant',
        'bedroom',
        'candlelight tables',
        'bedrooms',
    ],      
}
