wealthSoaps = {'activities': ['Investing',
                           'Business',
                           '{}',
                           '{}',
                           'eating at expensive restaurants',
                           'flying first class',
                           'buying a home',
                           'going on vacation',
                           'golfing',
                           'boating'],
            'objects': ['Money',
                        'Gold',
                        '{}',
                        '{}',
                        'gold',
                        'jewels',
                        'money',
                        'stocks',
                        'watch',
                        'suit'],
            'people': ['Stockbroker',
                       'Entrepreneur',
                       '{}',
                       '{}',
                       'CEO: treating company to dinner',
                       'investment banker: taking care of investment money',
                       'banker: open up an account',
                       'broker: trading stocks',
                       'Donald Trump: businessman',
                       'Martin Shkreli: investor'],
            'settings': ['Fine dining',
                         'Laying on Caribbean Beach',
                         '{}',
                         '{}',
                         'yacht',
                         'fancy restaurant',
                         'bank',
                         'stock brokers office',
                         'country club',
                         'office building']}