winterSoaps = {
    objects: [
        'snow',
        'christmas lights',
        'Snowman',
        'Boots',
        'snow',
        'ice',
        'snow',
        'ice skates',
        'Snow',
        'Christmas',
    ],
    people: [
        'parents: giving presents',
        'children: decorating tree',
        'Dad: Shoveling snow',
        'Mom: Adding logs to a fireplace.',
        'kids :sledding',
        'parents and kids:snowman',
        'dad: clearing driveway',
        'kids: playing in the snow',
        'Santa Claus',
        'Menorah'
    ],
    activities: [
        'making snowmen',
        'sledding',
        'Building an igloo',
        'Making hot chocolate',
        'sledding',
        'building a snowman',
        'shoveling snow in driveway',
        'going ice skating with family',
        'Sledding',
        'Skiing'
    ],
    settings: [
        'snowy field',
        'warm fireplace',
        'A frozen lake',
        'A cozy cabin',
        'outside on a hill in a park (sledding)',
        'outside in front of the house',
        'driveway of house',
        'ice skating rink',
        'Snowy landscape',
        'Snow-capped mountains',
    ],      
}
