writingSoaps = {'activities': ['using a typewriter',
                            'sitting at a desk',
                            'taking notes',
                            'writing a letter',
                            'Jotting down a plot idea',
                            'Scribbling a masterpiece',
                            'writing an essay',
                            'filling in a form',
                            'reporting the news',
                            'authoring a book'],
             'objects': ['writing utensil',
                         'books',
                         'paper',
                         'pencil',
                         'Pencil',
                         'Paper',
                         'pencil',
                         'paper',
                         'paper',
                         'typewriter'],
             'people': ['journalist gathering the scoop on current events',
                        'author editing a manuscript',
                        'student: studying for a test',
                        'secretary: writing memo to boss',
                        'Author: Creating a story',
                        'Poet: Rhyming words together',
                        'student: writing exam',
                        'writer: scribbling notes',
                        'novelist: writing books',
                        'reporter: writing news articles'],
             'settings': ['coffee shop',
                          'home office',
                          'college lecture hall',
                          'business office',
                          'A quiet cabin',
                          'A park bench by a tree',
                          'classroom',
                          'office',
                          'office',
                          'typing on a computer at a cafe']}